### ISSUE TITLE
add example files

### ISSUE THREAD

**Issue by nagordon** [DLR-AE/LoadsKernel#19]
Would it be possible to include a few examples, as indicated in your README? 

https://github.com/DLR-AE/LoadsKernel?tab=readme-ov-file#tutorials

The example here is a useful outline,  but of limited use without the Discus2c files

https://github.com/DLR-AE/LoadsKernel/blob/master/doc/tutorials/first_steps.ipynb

I am excited to explore these tools. Nice work!

**Comment by ArneVoss** [comment]
Hello Neal, 
no Problem and thank you for your interest! 
Just a short update: I'm currently working with a student to create an example (the DC3 aircraft), which will become available when his master thesis is finished. We just started, so that will be probably in mid-2024.
